'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Event_StudentMapping
    Public Property Event_StudentId As Integer
    Public Property EventId As Nullable(Of Integer)
    Public Property StudentId As Nullable(Of Integer)

    Public Overridable Property [Event] As [Event]
    Public Overridable Property Student As Student

End Class
