'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class SchoolManagementEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SchoolManagementEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Event_StudentMapping() As DbSet(Of Event_StudentMapping)
    Public Overridable Property Events() As DbSet(Of [Event])
    Public Overridable Property Students() As DbSet(Of Student)
    Public Overridable Property UserCredentails() As DbSet(Of UserCredentail)

End Class
