'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UserCredentail
    Public Property UserId As Integer
    Public Property FirstName As String
    Public Property LastName As String
    Public Property UserName As String
    Public Property Password As String
    Public Property CreatedDate As Nullable(Of Date)

End Class
