//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPISample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.GoalSubmissions = new HashSet<GoalSubmission>();
            this.EmpManagerMappings = new HashSet<EmpManagerMapping>();
        }
    
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ICollection<GoalSubmission> GoalSubmissions { get; set; }
        public virtual ICollection<EmpManagerMapping> EmpManagerMappings { get; set; }
    }
}
