//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPISample
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoalSubmission
    {
        public int SubmissionId { get; set; }
        public Nullable<int> GoalId { get; set; }
        public string Answer { get; set; }
        public Nullable<int> SubmittedBy { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Goal Goal { get; set; }
    }
}
