//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPISample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goal
    {
        public Goal()
        {
            this.GoalSubmissions = new HashSet<GoalSubmission>();
        }
    
        public int GoalId { get; set; }
        public string GoalDescription { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ICollection<GoalSubmission> GoalSubmissions { get; set; }
    }
}
