//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPISample
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrgDBEntities : DbContext
    {
        public OrgDBEntities()
            : base("name=OrgDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Goal> Goals { get; set; }
        public DbSet<GoalSubmission> GoalSubmissions { get; set; }
        public DbSet<EmpManagerMapping> EmpManagerMappings { get; set; }
    }
}
